[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  # Ensure a compatible Node version on Netlify if needed
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
